import React, { createContext, useContext, useState, useEffect } from 'react';
import { useAuth } from './AuthContext';

const LanguageContext = createContext();

export const translations = {
    ENGLISH: {
        "nav.overview": "Overview",
        "nav.analytics": "Analytics",
        "nav.transactions": "Transactions",
        "nav.users": "Users",
        "nav.settings": "Settings",
        "nav.logout": "Logout",

        "login.checkData": "Check your data and try again.",
        "login.heroTitle1": "Take control of your",
        "login.heroTitle2": "financial future",
        "login.heroSubtitle": "Visualize your savings, plan your goals, and make your money work for you with the most intuitive and secure tool.",
        "login.security": "Maximum security",
        "login.securityDesc": "Your data is encrypted",
        "login.growth": "Smart growth",
        "login.growthDesc": "Real-time analytics",
        "login.createAccount": "Create account",
        "login.signIn": "Sign In",
        "login.enterDetails": "Enter your details to register",
        "login.signInDesc": "Sign in to your account to continue",
        "login.username": "Username",
        "login.usernamePlaceholder": "Your username",
        "login.email": "Email",
        "login.emailPlaceholder": "you@example.com",
        "login.password": "Password",
        "login.alreadyHaveAccount": "Already have an account?",
        "login.noAccount": "Don't track your savings yet?",
        "login.checkData": "Please check your login data and try again",
        "login.error": "An unexpected error occurred",
        "login.forgotPasswordTitle": "Forgot password?",
        "login.forgotPasswordText": "To reset your password, please contact the system administrator.",

        "dashboard.overview": "Overview",
        "dashboard.welcome": "Welcome back, {0}",
        "dashboard.welcomeMobile": "Welcome, {0} ",
        "dashboard.totalBalance": "Total balance",
        "dashboard.vsLastMonth": "vs last month",
        "dashboard.monthlyIncome": "Monthly income",
        "dashboard.monthlyExpenses": "Monthly expenses",
        "dashboard.analytics": "Analytics",
        "dashboard.incomeVsExpenses": "Income vs Expenses",
        "dashboard.thisYear": "This year",
        "dashboard.last6Months": "Last 6 months",
        "dashboard.thisMonth": "This month",
        "dashboard.recentTransactions": "Recent transactions",
        "dashboard.seeAll": "See all",
        "dashboard.noTransactions": "No transactions found.",

        "analytics.title": "Advanced Analytics",
        "analytics.subtitle": "In-depth study of your financial health",
        "analytics.thismonth": "This Month",
        "analytics.last3months": "Last 3 Months",
        "analytics.last6months": "Last 6 Months",
        "analytics.thisyear": "This Year",
        "analytics.custom": "Custom Range",
        "analytics.from": "From",
        "analytics.to": "To",
        "analytics.totalIncome": "Total Income",
        "analytics.totalExpenses": "Total Expenses",
        "analytics.netBalance": "Net Balance",
        "analytics.trendTitle": "Income vs Expenses Trend",
        "analytics.categoryTitle": "Expenses by Category",
        "analytics.distributionTitle": "Expense Distribution",
        "analytics.distributionDesc": "Percentage of monthly spending",
        "analytics.insightTitle": "Financial Insight",
        "analytics.insightPerfect": "Excellent work! Your savings rate is healthy. Your expenditure on \"{0}\" is your highest cost at {1}{2}. Keep it up!",
        "analytics.insightGood": "You're on the right track, but there's room for improvement. Reducing your spending on \"{0}\" ({1}{2}) could significantly boost your savings score.",
        "analytics.insightBad": "Warning: Your expenditures are high relative to your income. Your spending on \"{0}\" ({1}{2}) accounts for a large portion of your budget. Consider a strict review.",
        "analytics.insightNoExpenses": "Incredible! You have recorded income but no expenses for this period. You are in a perfect position to invest or save.",
        "analytics.insightEmpty": "No expense data found in the selected period. Start logging your daily transactions to see powerful analytics!",
        "analytics.savingsScore": "Savings Score: {0}/100",

        "transactions.hub": "Transactions Hub",
        "transactions.hubDesc": "Manage all your operations and categories",
        "transactions.tabTransactions": "Transactions",
        "transactions.tabCategories": "Categories",
        "transactions.title": "Your transactions",
        "transactions.new": "New transaction",
        "transactions.errorSave": "Error saving transaction: {0}",
        "transactions.confirmDeleteTitle": "Are you sure?",
        "transactions.confirmDelete": "Are you sure you want to delete this transaction?",
        "transactions.errorDelete": "Failed to delete transaction",
        "transactions.updated": "Transaction updated successfully",
        "transactions.saved": "Transaction saved successfully",
        "transactions.deletedMsg": "Transaction has been removed.",
        "transactions.searchPlaceholder": "Search description or category...",
        "transactions.to": "to",
        "transactions.filterTitle": "Filter by date",
        "transactions.reset": "Reset",
        "transactions.empty": "No transactions. Register your first one!",
        "transactions.colDate": "Date",
        "transactions.colDescription": "Description",
        "transactions.colCategory": "Category",
        "transactions.colAmount": "Amount",
        "transactions.colActions": "Actions",
        "transactions.uncategorized": "Uncategorized",
        "transactions.defaultDesc": "Transaction",
        "transactions.page": "Page",
        "transactions.of": "of",
        "transactions.prev": "Previous",
        "transactions.next": "Next",
        "transactions.edit": "Edit transaction",
        "transactions.typeLabel": "Type",
        "transactions.expense": "Expense",
        "transactions.income": "Income",
        "transactions.amountLabel": "Amount",
        "transactions.amountPlaceholder": "0.00",
        "transactions.descLabel": "Description",
        "transactions.descPlaceholder": "e.g. Weekly groceries",
        "transactions.dateLabel": "Date",
        "transactions.categoryLabel": "Category",
        "transactions.selectCategory": "Select category...",
        "transactions.manualEntry": "Manual Entry",
        "transactions.generalCategory": "General",
        "transactions.dateFilters": "Date filters",
        "transactions.descOptional": "Description (optional)",
        "transactions.whatFor": "What was this for?",
        "transactions.newExpense": "Add expense",
        "transactions.newIncome": "Add income",
        "transactions.history": "Transaction history",
        "transactions.matches": "Matches found",
        "transactions.fastSearch": "Quick search by description...",

        "categories.title": "Your categories",
        "categories.new": "New category",
        "categories.empty": "No categories found. Create your first category!",
        "categories.errorSave": "Failed to save category",
        "categories.confirmDeleteTitle": "Are you sure?",
        "categories.confirmDelete": "Are you sure you want to delete this category?",
        "categories.errorDelete": "Failed to delete category",
        "categories.updated": "Category updated successfully",
        "categories.created": "Category created successfully",
        "categories.deletedMsg": "Category has been removed.",
        "categories.income": "Income",
        "categories.expense": "Expense",
        "categories.edit": "Edit category",
        "categories.existing": "Existing categories",
        "categories.saved": "Category saved successfully",
        "categories.nameLabel": "Category name",
        "categories.namePlaceholder": "e.g. Groceries",
        "categories.typeLabel": "Type",
        "categories.colorLabel": "Color accent",

        "users.title": "User management",
        "users.users": "Users",
        "users.subtitle": "Manage all registered users in the platform",
        "users.id": "ID",
        "users.username": "Username",
        "users.email": "Email",
        "users.actions": "Actions",
        "users.changePassword": "Change password",
        "users.delete": "Delete account",
        "users.confirmDelete": "Are you sure you want to permanently delete this user?",
        "users.errorFetch": "Failed to load users",
        "users.errorDelete": "Failed to delete user",
        "users.errorPassword": "Failed to update password",
        "users.newPassword": "New password",
        "users.passwordUpdated": "Password updated successfully",
        "users.userDeleted": "User deleted successfully",
        "users.deleteConfirm": "Are you sure you want to delete user \"{0}\"?",
        "users.deleteSuccess": "User deleted successfully",
        "users.updatePassword": "Set a new password for \"{0}\"",
        "users.passwordPlaceholder": "Enter new password...",
        "users.passwordEmpty": "Password cannot be empty",
        "users.passwordShort": "Password must be at least 8 characters",
        "users.passwordSuccess": "Password updated successfully",
        "users.admin": "Admin",
        "users.user": "User",
        "users.refresh": "Refresh",
        "users.noUsers": "No users found in the system.",

        "common.cancel": "Cancel",
        "common.update": "Update",
        "common.create": "Create",
        "common.save": "Save",
        "common.success": "Success!",
        "common.error": "Error",
        "common.deleted": "Deleted!",
        "common.delete": "Delete",
        "common.invalidAmount": "Please enter a valid amount greater than 0",
        "common.loading": "Loading...",
        "common.all": "All",
        "common.invalidAmount": "Please enter a valid amount greater than 0",

        "settings.title": "Settings",
        "settings.subtitle": "Manage your account preferences and settings",
        "settings.personalInfo": "Personal information",
        "settings.username": "Username",
        "settings.email": "Email address",
        "settings.appPreferences": "App preferences",
        "settings.currency": "Currency",
        "settings.currencyDesc": "Select your default display currency",
        "settings.language": "Language",
        "settings.languageDesc": "Application UI language",
        "settings.theme": "Theme",
        "settings.themeDesc": "Customize your UI variant",
        "settings.saveAll": "Save all changes",
        "settings.security": "Password & security",
        "settings.securityRec": "Security recommendation",
        "settings.securityDesc": "Ensure your account is secure by using a password that includes at least 8 characters, a mix of uppercase and lowercase letters, symbols, and numbers.",
        "settings.currentPassword": "Current password",
        "settings.newPassword": "New password",
        "settings.confirmPassword": "Confirm new password",
        "settings.forgotPassword": "Forgot password?",
        "settings.updatePassword": "Update password",
        "settings.updateSuccess": "Profile updated successfully",
        "settings.updateError": "Error updating profile",
        "settings.passwordShort": "New password must be at least 8 characters long.",
        "settings.passwordMismatch": "Passwords do not match",
        "settings.passwordSuccess": "Password changed successfully",
        "settings.passwordError": "Error changing password. Check your current password.",

        "lang.english": "English",
        "lang.spanish": "Spanish",
        "lang.french": "French",
        "lang.german": "German",
        "lang.italian": "Italian",
        "lang.portuguese": "Portuguese"
    },
    SPANISH: {
        "nav.overview": "Resumen",
        "nav.analytics": "Analíticas",
        "nav.transactions": "Transacciones",
        "nav.users": "Usuarios",
        "nav.settings": "Ajustes",
        "nav.logout": "Cerrar sesión",

        "login.checkData": "Comprueba tus datos e inténtalo de nuevo.",
        "login.heroTitle1": "Toma el control de tu",
        "login.heroTitle2": "futuro financiero",
        "login.heroSubtitle": "Visualiza tus ahorros, planifica tus metas y haz que tu dinero trabaje para ti con la herramienta más intuitiva y segura.",
        "login.security": "Máxima seguridad",
        "login.securityDesc": "Tus datos están encriptados",
        "login.growth": "Crecimiento inteligente",
        "login.growthDesc": "Analíticas en tiempo real",
        "login.createAccount": "Crear cuenta",
        "login.signIn": "Iniciar sesión",
        "login.enterDetails": "Introduce tus detalles para registrarte",
        "login.signInDesc": "Inicia sesión en tu cuenta para continuar",
        "login.username": "Nombre de usuario",
        "login.usernamePlaceholder": "Tu usuario",
        "login.email": "Correo",
        "login.emailPlaceholder": "tu@correo.com",
        "login.password": "Contraseña",
        "login.alreadyHaveAccount": "¿Ya tienes una cuenta?",
        "login.noAccount": "¿Aún no rastreas tus ahorros?",
        "login.checkData": "Por favor revisa tus datos de acceso e intenta de nuevo",
        "login.error": "Ocurrió un error inesperado",
        "login.forgotPasswordTitle": "¿Olvidaste tu contraseña?",
        "login.forgotPasswordText": "Por favor, contacta con el administrador del sistema para cambiar tu contraseña.",

        "dashboard.overview": "Resumen",
        "dashboard.welcome": "Bienvenido, {0}",
        "dashboard.welcomeMobile": "Bienvenido, {0} ",
        "dashboard.totalBalance": "Balance total",
        "dashboard.vsLastMonth": "vs mes anterior",
        "dashboard.monthlyIncome": "Ingresos mensuales",
        "dashboard.monthlyExpenses": "Gastos mensuales",
        "dashboard.analytics": "Analíticas",
        "dashboard.incomeVsExpenses": "Ingresos vs Gastos",
        "dashboard.thisYear": "Este año",
        "dashboard.last6Months": "Últimos 6 meses",
        "dashboard.thisMonth": "Este mes",
        "dashboard.recentTransactions": "Transacciones recientes",
        "dashboard.seeAll": "Ver todas",
        "dashboard.noTransactions": "No se encontraron transacciones.",

        "analytics.title": "Analíticas avanzadas",
        "analytics.subtitle": "Estudio en profundidad de tu salud financiera",
        "analytics.thismonth": "Este mes",
        "analytics.last3months": "Últimos 3 meses",
        "analytics.last6months": "Últimos 6 meses",
        "analytics.thisyear": "Este año",
        "analytics.custom": "Personalizado",
        "analytics.from": "Desde",
        "analytics.to": "Hasta",
        "analytics.totalIncome": "Ingresos totales",
        "analytics.totalExpenses": "Gastos totales",
        "analytics.netBalance": "Balance neto",
        "analytics.trendTitle": "Tendencia ingresos vs gastos",
        "analytics.categoryTitle": "Gastos por categoría",
        "analytics.distributionTitle": "Distribución de gastos",
        "analytics.distributionDesc": "Porcentaje del gasto mensual",
        "analytics.insightTitle": "Idea financiera",
        "analytics.insightPerfect": "¡Excelente trabajo! Tu tasa de ahorro es saludable. Aun así, tu gasto en \"{0}\" es tu mayor coste con {1}{2}. ¡Sigue así!",
        "analytics.insightGood": "Vas por el buen camino, pero hay margen de mejora. Reducir tu gasto en \"{0}\" ({1}{2}) podría aumentar significativamente tu puntuación de ahorro.",
        "analytics.insightBad": "Alerta: Tus gastos son altos en relación con tus ingresos. Tu gasto en \"{0}\" ({1}{2}) se lleva una gran parte de tu presupuesto. Considera una revisión estricta.",
        "analytics.insightNoExpenses": "¡Increíble! Has registrado ingresos pero no gastos en este periodo. Estás en una posición perfecta para invertir o ahorrar.",
        "analytics.insightEmpty": "No se encontraron datos de gastos en el periodo seleccionado. ¡Empieza a registrar tus transacciones diarias para ver analíticas poderosas!",
        "analytics.savingsScore": "Puntuación de ahorro: {0}/100",

        "transactions.hub": "Centro de transacciones",
        "transactions.hubDesc": "Gestiona todas tus operaciones y categorías",
        "transactions.tabTransactions": "Transacciones",
        "transactions.tabCategories": "Categorías",
        "transactions.title": "Tus transacciones",
        "transactions.new": "Nueva transacción",
        "transactions.errorSave": "Error al guardar transacción: {0}",
        "transactions.confirmDeleteTitle": "¿Estás seguro?",
        "transactions.confirmDelete": "¿Estás seguro de que deseas eliminar esta transacción?",
        "transactions.errorDelete": "Error al eliminar transacción",
        "transactions.updated": "Transacción actualizada correctamente",
        "transactions.saved": "Transacción guardada correctamente",
        "transactions.deletedMsg": "La transacción ha sido eliminada.",
        "transactions.searchPlaceholder": "Buscar descripción o categoría...",
        "transactions.to": "a",
        "transactions.filterTitle": "Filtrar por fecha",
        "transactions.reset": "Reset",
        "transactions.empty": "No hay transacciones. ¡Registra tu primera transacción!",
        "transactions.colDate": "Fecha",
        "transactions.colDescription": "Descripción",
        "transactions.colCategory": "Categoría",
        "transactions.colAmount": "Cantidad",
        "transactions.colActions": "Actions",
        "transactions.uncategorized": "Sin categoría",
        "transactions.defaultDesc": "Transacción",
        "transactions.page": "Página",
        "transactions.of": "de",
        "transactions.prev": "Anterior",
        "transactions.next": "Siguiente",
        "transactions.edit": "Editar transacción",
        "transactions.typeLabel": "Tipo",
        "transactions.expense": "Gasto",
        "transactions.income": "Ingreso",
        "transactions.amountLabel": "Cantidad",
        "transactions.amountPlaceholder": "0.00",
        "transactions.descLabel": "Descripción",
        "transactions.descPlaceholder": "ej. Compras de la semana",
        "transactions.descOptional": "Descripción (opcional)",
        "transactions.whatFor": "¿Para qué fue esto?",
        "transactions.dateLabel": "Fecha",
        "transactions.categoryLabel": "Categoría",
        "transactions.selectCategory": "Seleccionar categoría...",
        "transactions.manualEntry": "Entrada manual",
        "transactions.generalCategory": "General",
        "transactions.dateFilters": "Filtros de fecha",
        "transactions.descOptional": "Descripción (opcional)",
        "transactions.whatFor": "¿Para qué fue esto?",
        "transactions.newExpense": "Añadir gasto",
        "transactions.newIncome": "Añadir ingreso",
        "transactions.history": "Historial de transacciones",
        "transactions.matches": "Coincidencias",
        "transactions.fastSearch": "Búsqueda rápida por descripción...",

        "categories.title": "Tus categorías",
        "categories.new": "Nueva categoría",
        "categories.empty": "No se encontraron categorías. ¡Crea una!",
        "categories.errorSave": "Error al guardar categoría",
        "categories.confirmDeleteTitle": "¿Estás seguro?",
        "categories.confirmDelete": "¿Estás seguro de que deseas eliminar esta categoría?",
        "categories.errorDelete": "Error al eliminar categoría",
        "categories.updated": "Categoría actualizada correctamente",
        "categories.created": "Categoría creada correctamente",
        "categories.deletedMsg": "La categoría ha sido eliminada.",
        "categories.income": "Ingreso",
        "categories.expense": "Gasto",
        "categories.edit": "Editar categoría",
        "categories.existing": "Categorías existentes",
        "categories.saved": "Categoría guardada correctamente",
        "categories.nameLabel": "Nombre de categoría",
        "categories.namePlaceholder": "ej. Compras",
        "categories.typeLabel": "Tipo",
        "categories.colorLabel": "Acento de color",

        "users.title": "Gestión de usuarios",
        "users.users": "Usuarios",
        "users.subtitle": "Administrar todos los usuarios registrados en la plataforma",
        "users.id": "ID",
        "users.username": "Usuario",
        "users.email": "Correo",
        "users.actions": "Acciones",
        "users.changePassword": "Cambiar contraseña",
        "users.delete": "Eliminar cuenta",
        "users.confirmDelete": "¿Estás seguro de que deseas eliminar permanentemente a este usuario?",
        "users.errorFetch": "Error al cargar usuarios",
        "users.errorDelete": "Error al eliminar usuario",
        "users.errorPassword": "Error al actualizar la contraseña",
        "users.newPassword": "Nueva contraseña",
        "users.passwordUpdated": "Contraseña actualizada correctamente",
        "users.userDeleted": "Usuario eliminado correctamente",
        "users.deleteConfirm": "¿Estás seguro de que deseas eliminar al usuario \"{0}\"?",
        "users.deleteSuccess": "Usuario eliminado correctamente",
        "users.updatePassword": "Establecer nueva contraseña para \"{0}\"",
        "users.passwordPlaceholder": "Introduce la nueva contraseña...",
        "users.passwordEmpty": "La contraseña no puede estar vacía",
        "users.passwordShort": "La contraseña debe tener al menos 8 caracteres",
        "users.passwordSuccess": "Contraseña actualizada correctamente",
        "users.admin": "Administrador",
        "users.user": "Usuario",
        "users.refresh": "Refrescar",
        "users.noUsers": "No se encontraron usuarios en el sistema.",

        "common.cancel": "Cancelar",
        "common.update": "Actualizar",
        "common.create": "Crear",
        "common.save": "Guardar",
        "common.success": "¡Éxito!",
        "common.error": "Error",
        "common.deleted": "¡Eliminado!",
        "common.delete": "Eliminar",
        "common.loading": "Cargando...",
        "common.all": "Todos",
        "common.invalidAmount": "Por favor, introduce una cantidad válida mayor que 0",

        "settings.title": "Ajustes",
        "settings.subtitle": "Gestiona tus preferencias y ajustes de cuenta",
        "settings.personalInfo": "Información personal",
        "settings.username": "Nombre de usuario",
        "settings.email": "Dirección de correo",
        "settings.appPreferences": "Preferencias de la aplicación",
        "settings.currency": "Moneda",
        "settings.currencyDesc": "Selecciona tu moneda de visualización predeterminada",
        "settings.language": "Idioma",
        "settings.languageDesc": "Idioma de la interfaz de usuario",
        "settings.theme": "Tema",
        "settings.themeDesc": "Personaliza tu variante de interfaz",
        "settings.saveAll": "Guardar todos los cambios",
        "settings.security": "Contraseña y seguridad",
        "settings.securityRec": "Recomendación de seguridad",
        "settings.securityDesc": "Asegúrate de que tu cuenta sea segura utilizando una contraseña que incluya al menos 8 caracteres, una mezcla de letras mayúsculas y minúsculas, símbolos y números.",
        "settings.currentPassword": "Contraseña actual",
        "settings.newPassword": "Nueva contraseña",
        "settings.confirmPassword": "Confirmar nueva contraseña",
        "settings.forgotPassword": "¿Olvidaste tu contraseña?",
        "settings.updatePassword": "Actualizar contraseña",
        "settings.updateSuccess": "Perfil actualizado correctamente",
        "settings.updateError": "Error al actualizar el perfil",
        "settings.passwordShort": "La nueva contraseña debe tener al menos 8 caracteres.",
        "settings.passwordMismatch": "Las contraseñas no coinciden",
        "settings.passwordSuccess": "Contraseña cambiada correctamente",
        "settings.passwordError": "Error al cambiar la contraseña. Verifica tu contraseña actual.",

        "lang.english": "Inglés",
        "lang.spanish": "Español",
        "lang.french": "Francés",
        "lang.german": "Alemán",
        "lang.italian": "Italiano",
        "lang.portuguese": "Portugués"
    },
    FRENCH: {
        "nav.overview": "Aperçu",
        "nav.analytics": "Analytique",
        "nav.transactions": "Transactions",
        "nav.users": "Utilisateurs",
        "nav.settings": "Paramètres",
        "nav.logout": "Se déconnecter",
        "login.checkData": "Vérifiez vos données et réessayez.",
        "login.heroTitle1": "Prenez le contrôle de votre",
        "login.heroTitle2": "avenir financier",
        "login.heroSubtitle": "Visualisez vos économies, planifiez et faites travailler votre argent.",
        "login.security": "Sécurité maximale",
        "login.securityDesc": "Vos données sont chiffrées",
        "login.growth": "Croissance intelligente",
        "login.growthDesc": "Analytique en temps réel",
        "login.createAccount": "Créer un compte",
        "login.signIn": "S'identifier",
        "login.enterDetails": "Entrez vos détails pour vous inscrire",
        "login.signInDesc": "Connectez-vous pour continuer",
        "login.username": "Nom d'utilisateur",
        "login.usernamePlaceholder": "Votre nom d'utilisateur",
        "login.email": "E-mail",
        "login.emailPlaceholder": "votre@email.com",
        "login.password": "Mot de passe",
        "login.alreadyHaveAccount": "Vous avez déjà un compte ?",
        "login.noAccount": "Pas encore de compte ?",
        "dashboard.overview": "Aperçu",
        "dashboard.welcome": "Bon retour, {0}",
        "dashboard.welcomeMobile": "Bon retour, {0} ",
        "dashboard.totalBalance": "Solde total",
        "dashboard.vsLastMonth": "vs mois dernier",
        "dashboard.monthlyIncome": "Revenu mensuel",
        "dashboard.monthlyExpenses": "Dépenses mensuelles",
        "dashboard.analytics": "Analytique",
        "dashboard.incomeVsExpenses": "Revenus vs Dépenses",
        "dashboard.thisYear": "Cette année",
        "dashboard.last6Months": "Les 6 derniers mois",
        "dashboard.thisMonth": "Ce mois-ci",
        "dashboard.recentTransactions": "Transactions récentes",
        "dashboard.seeAll": "Voir tout",
        "dashboard.noTransactions": "Aucune transaction trouvée.",
        "analytics.title": "Analytique avancée",
        "analytics.subtitle": "Examen approfondi de votre santé financière",
        "analytics.thismonth": "Ce mois-ci",
        "analytics.last3months": "Derniers 3 mois",
        "analytics.last6months": "Derniers 6 mois",
        "analytics.thisyear": "Cette année",
        "analytics.custom": "Personnalisé",
        "analytics.from": "De",
        "analytics.to": "À",
        "analytics.totalIncome": "Revenu total",
        "analytics.totalExpenses": "Dépenses totales",
        "analytics.netBalance": "Solde net",
        "analytics.trendTitle": "Tendance revenus vs dépenses",
        "analytics.categoryTitle": "Dépenses par catégorie",
        "analytics.distributionTitle": "Répartition des dépenses",
        "analytics.distributionDesc": "Part des dépenses mensuelles",
        "analytics.insightTitle": "Aperçu financier",
        "analytics.insightMessage": "Votre plus grande dépense est \"{0}\" pour {1}{2}. Révisez ceci pour optimiser vos économies.",
        "analytics.insightEmpty": "Aucune donnée de dépense. Commencez à enregistrer vos transactions !",
        "analytics.savingsScore": "Score d'épargne: {0}/100",
        "transactions.hub": "Centre de transactions",
        "transactions.hubDesc": "Gérez toutes vos opérations et catégories",
        "transactions.tabTransactions": "Transactions",
        "transactions.tabCategories": "Catégories",
        "transactions.title": "Vos transactions",
        "transactions.new": "Nouvelle transaction",
        "transactions.errorSave": "Échec de l'enregistrement : {0}",
        "transactions.confirmDeleteTitle": "Êtes-vous sûr ?",
        "transactions.confirmDelete": "Voulez-vous supprimer cette transaction ?",
        "transactions.errorDelete": "Échec de la suppression",
        "transactions.updated": "Transaction mise à jour",
        "transactions.saved": "Transaction enregistrée",
        "transactions.deletedMsg": "La transaction a été supprimée.",
        "transactions.searchPlaceholder": "Rechercher...",
        "transactions.to": "à",
        "transactions.filterTitle": "Filtrer par date",
        "transactions.reset": "Réinitialiser",
        "transactions.empty": "Aucune transaction. Enregistrez-en une !",
        "transactions.colDate": "Date",
        "transactions.colDescription": "Description",
        "transactions.colCategory": "Catégorie",
        "transactions.colAmount": "Montant",
        "transactions.colActions": "Actions",
        "transactions.uncategorized": "Non catégorisé",
        "transactions.defaultDesc": "Transaction",
        "transactions.page": "Page",
        "transactions.of": "sur",
        "transactions.prev": "Précédent",
        "transactions.next": "Suivant",
        "transactions.edit": "Modifier la transaction",
        "transactions.typeLabel": "Type",
        "transactions.expense": "Dépense",
        "transactions.income": "Revenu",
        "transactions.amountLabel": "Montant",
        "transactions.amountPlaceholder": "0.00",
        "transactions.descLabel": "Description",
        "transactions.descPlaceholder": "ex: Courses",
        "transactions.descOptional": "Description (facultatif)",
        "transactions.whatFor": "À quoi cela a-t-il servi ?",
        "transactions.dateLabel": "Date",
        "transactions.categoryLabel": "Catégorie",
        "transactions.selectCategory": "Sélectionnez...",
        "categories.title": "Vos catégories",
        "categories.new": "Nouvelle catégorie",
        "categories.empty": "Aucune catégorie. Créez-en une !",
        "categories.errorSave": "Échec",
        "categories.confirmDelete": "Supprimer la catégorie ?",
        "categories.errorDelete": "Échec",
        "categories.income": "Revenu",
        "categories.expense": "Dépense",
        "categories.edit": "Modifier la catégorie",
        "categories.nameLabel": "Nom de la catégorie",
        "categories.namePlaceholder": "ex: Courses",
        "categories.typeLabel": "Type",
        "categories.colorLabel": "Couleur d'accentuation",
        "users.title": "Gestion des utilisateurs",
        "users.users": "Utilisateurs",
        "users.subtitle": "Gérez tous les utilisateurs",
        "users.id": "ID",
        "users.username": "Nom d'utilisateur",
        "users.email": "E-mail",
        "users.actions": "Actions",
        "users.changePassword": "Changer mot de passe",
        "users.delete": "Supprimer le compte",
        "users.confirmDelete": "Êtes-vous sûr de vouloir supprimer cet utilisateur ?",
        "users.errorFetch": "Échec du chargement des utilisateurs",
        "users.errorDelete": "Échec de la suppression de l'utilisateur",
        "users.errorPassword": "Échec de la mise à jour du mot de passe",
        "users.newPassword": "Nouveau mot de passe",
        "users.passwordUpdated": "Mot de passe mis à jour avec succès",
        "users.userDeleted": "Utilisateur supprimé avec succès",
        "users.deleteConfirm": "Voulez-vous vraiment supprimer l'utilisateur \"{0}\" ?",
        "users.deleteSuccess": "Utilisateur supprimé avec succès",
        "users.updatePassword": "Définir un mot de passe pour \"{0}\"",
        "users.passwordPlaceholder": "Entrez le nouveau mot de passe...",
        "users.passwordEmpty": "Le mot de passe ne peut pas être vide",
        "users.passwordShort": "Au moins 8 caractères",
        "users.passwordSuccess": "Mot de passe mis à jour",
        "users.admin": "Administrateur",
        "users.user": "Utilisateur",
        "users.refresh": "Actualiser",
        "users.noUsers": "Aucun utilisateur trouvé.",
        "common.cancel": "Annuler",
        "common.update": "Mettre à jour",
        "common.create": "Créer",
        "common.save": "Sauvegarder",
        "common.success": "Succès!",
        "common.error": "Erreur",
        "common.deleted": "Supprimé!",
        "common.delete": "Oui, supprimer!",
        "settings.title": "Paramètres",
        "settings.subtitle": "Gérez vos préférences",
        "settings.personalInfo": "Informations personnelles",
        "settings.username": "Nom d'utilisateur",
        "settings.email": "E-mail",
        "settings.appPreferences": "Préférences",
        "settings.currency": "Devise",
        "settings.currencyDesc": "Devise d'affichage",
        "settings.language": "Langue",
        "settings.languageDesc": "Langue de l'interface",
        "settings.theme": "Thème",
        "settings.themeDesc": "Thème visuel",
        "settings.saveAll": "Enregistrer",
        "settings.security": "Sécurité",
        "settings.securityRec": "Recommandation",
        "settings.securityDesc": "Utilisez au moins 8 caractères complexes.",
        "settings.currentPassword": "Mot de passe actuel",
        "settings.newPassword": "Nouveau",
        "settings.confirmPassword": "Confirmer",
        "settings.forgotPassword": "Oublié ?",
        "settings.updatePassword": "Mettre à jour",
        "transactions.newExpense": "Ajouter dépense",
        "transactions.newIncome": "Ajouter revenu",
        "transactions.history": "Historique des transactions",
        "transactions.matches": "Correspondances trouvées",
        "transactions.fastSearch": "Recherche rapide par description...",
        "common.all": "Tout",
        "common.invalidAmount": "Veuillez saisir un montant supérieur à 0",
        "lang.english": "Anglais",
        "lang.spanish": "Espagnol",
        "lang.french": "Français",
        "lang.german": "Allemand",
        "lang.italian": "Italien",
        "lang.portuguese": "Portugais"
    },
    GERMAN: {
        "nav.overview": "Übersicht",
        "nav.analytics": "Analytik",
        "nav.transactions": "Transaktionen",
        "nav.users": "Benutzer",
        "nav.settings": "Einstellungen",
        "nav.logout": "Abmelden",
        "login.checkData": "Überprüfen Sie Ihre Daten, versuchen Sie es erneut.",
        "login.heroTitle1": "Übernehmen Sie die Kontrolle über",
        "login.heroTitle2": "finanzielle Zukunft",
        "login.heroSubtitle": "Visualisieren Sie Ersparnisse, planen und machen Sie alles sicher.",
        "login.security": "Maximale Sicherheit",
        "login.securityDesc": "Ihre Daten sind verschlüsselt",
        "login.growth": "Intelligentes Wachstum",
        "login.growthDesc": "Echtzeit-Analysen",
        "login.createAccount": "Konto erstellen",
        "login.signIn": "Anmelden",
        "login.enterDetails": "Registrieren",
        "login.signInDesc": "Melden Sie sich an",
        "login.username": "Benutzername",
        "login.usernamePlaceholder": "Benutzername",
        "login.email": "E-Mail",
        "login.emailPlaceholder": "email@email.com",
        "login.password": "Passwort",
        "login.alreadyHaveAccount": "Bereits ein Konto?",
        "login.noAccount": "Noch kein Konto?",
        "dashboard.overview": "Übersicht",
        "dashboard.welcome": "Willkommen zurück, {0}",
        "dashboard.welcomeMobile": "Willkommen, {0} ",
        "dashboard.totalBalance": "Gesamtsaldo",
        "dashboard.monthlyIncome": "Monatliches Einkommen",
        "dashboard.monthlyExpenses": "Monatliche Ausgaben",
        "dashboard.vsLastMonth": "vs. letztem Monat",
        "dashboard.analytics": "Analytik",
        "dashboard.incomeVsExpenses": "Einnahmen vs Ausgaben",
        "dashboard.thisYear": "Dieses Jahr",
        "dashboard.last6Months": "Letzte 6 Monate",
        "dashboard.thisMonth": "Diesen Monat",
        "dashboard.recentTransactions": "Letzte Transaktionen",
        "dashboard.seeAll": "Alle sehen",
        "dashboard.noTransactions": "Keine Transaktionen gefunden.",
        "analytics.title": "Erweitere Analytik",
        "analytics.subtitle": "Detaillierter Einblick.",
        "analytics.thismonth": "Diesen Monat",
        "analytics.last3months": "Letz. 3 Monate",
        "analytics.last6months": "Letz. 6 Monate",
        "analytics.thisyear": "Dieses Jahr",
        "analytics.custom": "Benutzerdefiniert",
        "analytics.from": "Von",
        "analytics.to": "Bis",
        "analytics.totalIncome": "Gesamteinnahmen",
        "analytics.totalExpenses": "Gesamtausgaben",
        "analytics.netBalance": "Nettosaldo",
        "analytics.trendTitle": "Trend",
        "analytics.categoryTitle": "Ausgaben nach Kategorie",
        "analytics.distributionTitle": "Ausgabenverteilung",
        "analytics.distributionDesc": "Anteil an Ausgaben",
        "analytics.insightTitle": "Erkenntnis",
        "analytics.insightMessage": "Höchste Ausgabe \"{0}\" = {1}{2}. Bitte optimieren.",
        "analytics.insightEmpty": "Keine Daten.",
        "analytics.savingsScore": "Sparquote: {0}/100",
        "transactions.hub": "Transaktionen",
        "transactions.hubDesc": "Verwalten Sie Ihre Operationen",
        "transactions.tabTransactions": "Transaktionen",
        "transactions.tabCategories": "Kategorien",
        "transactions.title": "Ihre Transaktionen",
        "transactions.new": "Neue Transaktion",
        "transactions.errorSave": "Fehler beim Speichern: {0}",
        "transactions.confirmDeleteTitle": "Sind Sie sicher?",
        "transactions.confirmDelete": "Transaktion löschen?",
        "transactions.errorDelete": "Fehler beim Löschen",
        "transactions.updated": "Transaktion aktualisiert",
        "transactions.saved": "Transaktion gespeichert",
        "transactions.deletedMsg": "Transaktion wurde gelöscht.",
        "transactions.searchPlaceholder": "Suchen...",
        "transactions.to": "bis",
        "transactions.filterTitle": "Filter",
        "transactions.reset": "Zurücksetzen",
        "transactions.empty": "Keine Transaktionen.",
        "transactions.colDate": "Datum",
        "transactions.colDescription": "Beschreibung",
        "transactions.colCategory": "Kategorie",
        "transactions.colAmount": "Betrag",
        "transactions.colActions": "Aktionen",
        "transactions.uncategorized": "Unkategorisiert",
        "transactions.defaultDesc": "Transaktion",
        "transactions.page": "Seite",
        "transactions.of": "von",
        "transactions.prev": "Bisherige",
        "transactions.next": "Nächste",
        "transactions.edit": "Bearbeiten",
        "transactions.typeLabel": "Typ",
        "transactions.expense": "Ausgabe",
        "transactions.income": "Einkommen",
        "transactions.amountLabel": "Betrag",
        "transactions.amountPlaceholder": "0.00",
        "transactions.descLabel": "Beschreibung",
        "transactions.descPlaceholder": "z.B. Lebensmittel",
        "transactions.descOptional": "Beschreibung (optional)",
        "transactions.whatFor": "Wofür war das?",
        "transactions.dateLabel": "Datum",
        "transactions.categoryLabel": "Kategorie",
        "transactions.selectCategory": "Wählen...",
        "categories.title": "Ihre Kategorien",
        "categories.new": "Neue Kategorie",
        "categories.empty": "Keine Kategorien. Erste erstellen!",
        "categories.errorSave": "Fehler",
        "categories.confirmDelete": "Sicher?",
        "categories.errorDelete": "Fehler",
        "categories.income": "Einkommen",
        "categories.expense": "Ausgabe",
        "categories.edit": "Kategorie bearbeiten",
        "categories.nameLabel": "Name",
        "categories.namePlaceholder": "z.B. Lebensmittel",
        "categories.typeLabel": "Typ",
        "categories.colorLabel": "Farbe",
        "users.title": "Benutzerverwaltung",
        "users.users": "Benutzer",
        "users.subtitle": "Verwalten Sie alle Benutzer",
        "users.id": "ID",
        "users.username": "Benutzername",
        "users.email": "E-Mail",
        "users.actions": "Aktionen",
        "users.changePassword": "Passwort ändern",
        "users.delete": "Konto löschen",
        "users.confirmDelete": "Möchten Sie diesen Benutzer wirklich löschen?",
        "users.errorFetch": "Benutzer konnten nicht geladen werden",
        "users.errorDelete": "Fehler beim Löschen des Benutzers",
        "users.errorPassword": "Fehler beim Aktualisieren des Passworts",
        "users.newPassword": "Neues Passwort",
        "users.passwordUpdated": "Passwort erfolgreich aktualisiert",
        "users.userDeleted": "Benutzer erfolgreich gelöscht",
        "users.deleteConfirm": "Möchten Sie den Benutzer \"{0}\" wirklich löschen?",
        "users.deleteSuccess": "Benutzer erfolgreich gelöscht",
        "users.updatePassword": "Neues Passwort für \"{0}\" festlegen",
        "users.passwordPlaceholder": "Neues Passwort eingeben...",
        "users.passwordEmpty": "Passwort darf nicht leer sein",
        "users.passwordShort": "Mindestens 8 Zeichen erforderlich",
        "users.passwordSuccess": "Passwort aktualisiert",
        "users.admin": "Administrator",
        "users.user": "Benutzer",
        "users.refresh": "Aktualisieren",
        "users.noUsers": "Keine Benutzer gefunden.",
        "common.cancel": "Abbrechen",
        "common.update": "Aktualisieren",
        "common.create": "Erstellen",
        "common.save": "Speichern",
        "common.success": "Erfolg!",
        "common.error": "Fehler",
        "common.deleted": "Gelöscht!",
        "common.delete": "Ja, löschen!",
        "common.invalidAmount": "Bitte geben Sie einen gültigen Betrag größer als 0 ein",
        "settings.title": "Einstellungen",
        "settings.subtitle": "Präferenzen verwalten",
        "settings.personalInfo": "Persönliche Daten",
        "settings.username": "Benutzername",
        "settings.email": "E-Mail",
        "settings.appPreferences": "Präferenzen",
        "settings.currency": "Währung",
        "settings.currencyDesc": "Anzeigewährung",
        "settings.language": "Sprache",
        "settings.languageDesc": "UI-Sprache",
        "settings.theme": "Thema",
        "settings.themeDesc": "Visuelles Thema",
        "settings.saveAll": "Speichern",
        "settings.security": "Sicherheit",
        "settings.securityRec": "Empfehlung",
        "settings.securityDesc": "Mindestens 8 Zeichen.",
        "settings.currentPassword": "Aktuelles Passwort",
        "settings.newPassword": "Neues",
        "settings.confirmPassword": "Bestätigen",
        "settings.forgotPassword": "Vergessen?",
        "settings.updatePassword": "Aktualisieren",
        "transactions.newExpense": "Ausgabe hinzufügen",
        "transactions.newIncome": "Einnahme hinzufügen",
        "transactions.history": "Transaktionshistorie",
        "transactions.matches": "Treffer gefunden",
        "transactions.fastSearch": "Schnellsuche nach Beschreibung...",
        "common.all": "Alle",
        "common.invalidAmount": "Bitte geben Sie einen gültigen Betrag größer als 0 ein",
        "lang.english": "Englisch",
        "lang.spanish": "Spanisch",
        "lang.french": "Französisch",
        "lang.german": "Deutsch",
        "lang.italian": "Italienisch",
        "lang.portuguese": "Portugiesisch"
    },
    ITALIAN: {
        "nav.overview": "Panoramica",
        "nav.analytics": "Analitica",
        "nav.transactions": "Transazioni",
        "nav.users": "Utenti",
        "nav.settings": "Impostazioni",
        "nav.logout": "Esci",
        "login.checkData": "Controlla i tuoi dati.",
        "login.heroTitle1": "Prendi il controllo",
        "login.heroTitle2": "finanziario",
        "login.heroSubtitle": "Pianifica e risparmia.",
        "login.security": "Massima sicurezza",
        "login.securityDesc": "Crittografia avanzata",
        "login.growth": "Crescita",
        "login.growthDesc": "Risultati in tempo reale",
        "login.createAccount": "Crea account",
        "login.signIn": "Accedi",
        "login.enterDetails": "Registrati qui",
        "login.signInDesc": "Entra nel tuo account",
        "login.username": "Utente",
        "login.usernamePlaceholder": "Il tuo nome utente",
        "login.email": "Email",
        "login.emailPlaceholder": "email@email.com",
        "login.password": "Password",
        "login.alreadyHaveAccount": "Hai già un account?",
        "login.noAccount": "Nuovo utente?",
        "dashboard.overview": "Panoramica",
        "dashboard.welcome": "Bentornato, {0}",
        "dashboard.welcomeMobile": "Bentornato, {0} ",
        "dashboard.totalBalance": "Saldo totale",
        "dashboard.vsLastMonth": "vs mese scorso",
        "dashboard.monthlyIncome": "Entrate",
        "dashboard.monthlyExpenses": "Uscite",
        "dashboard.analytics": "Analitica",
        "dashboard.incomeVsExpenses": "Entrate vs Uscite",
        "dashboard.thisYear": "Quest'anno",
        "dashboard.last6Months": "Ultimi 6 mesi",
        "dashboard.thisMonth": "Questo mese",
        "dashboard.recentTransactions": "Recenti",
        "dashboard.seeAll": "Vedi tutto",
        "dashboard.noTransactions": "Nessuna transazione.",
        "analytics.title": "Analitica",
        "analytics.subtitle": "Sguardo approfondito.",
        "analytics.thismonth": "Questo mese",
        "analytics.last3months": "Ultimi 3 mesi",
        "analytics.last6months": "Ultimi 6 mesi",
        "analytics.thisyear": "Quest'anno",
        "analytics.custom": "Personalizzato",
        "analytics.from": "Da",
        "analytics.to": "A",
        "analytics.totalIncome": "Entrate",
        "analytics.totalExpenses": "Uscite",
        "analytics.netBalance": "Netto",
        "analytics.trendTitle": "Tendenza",
        "analytics.categoryTitle": "Uscite per categoria",
        "analytics.distributionTitle": "Distribuzione spese",
        "analytics.distributionDesc": "Quota uscite",
        "analytics.insightTitle": "Intuizione",
        "analytics.insightMessage": "Maggiore spesa è \"{0}\" {1}{2}.",
        "analytics.insightEmpty": "Nessun dato.",
        "analytics.savingsScore": "Punteggio: {0}/100",
        "transactions.hub": "Hub transazioni",
        "transactions.hubDesc": "Gestisci operazioni",
        "transactions.tabTransactions": "Transazioni",
        "transactions.tabCategories": "Categorie",
        "transactions.title": "Tue transazioni",
        "transactions.new": "Nuova transazione",
        "transactions.errorSave": "Errore: {0}",
        "transactions.confirmDeleteTitle": "Sei sicuro?",
        "transactions.confirmDelete": "Eliminare transazione?",
        "transactions.errorDelete": "Errore",
        "transactions.updated": "Transazione aggiornata",
        "transactions.saved": "Transazione salvata",
        "transactions.deletedMsg": "La transazione è stata eliminata.",
        "transactions.searchPlaceholder": "Cerca...",
        "transactions.to": "a",
        "transactions.filterTitle": "Filtro",
        "transactions.reset": "Reset",
        "transactions.empty": "Nessuna transazione trovata.",
        "transactions.updated": "Transazione aggiornata con successo",
        "transactions.saved": "Transazione salvata con successo",
        "transactions.confirmDeleteTitle": "Sei sicuro?",
        "transactions.deletedMsg": "La transazione è stata eliminata.",
        "transactions.updated": "Transazione aggiornata con successo",
        "transactions.saved": "Transazione salvata con successo",
        "transactions.confirmDeleteTitle": "Sei sicuro?",
        "transactions.deletedMsg": "La transazione è stata eliminata.",
        "transactions.amountPlaceholder": "0.00",
        "transactions.colDate": "Data",
        "transactions.colDescription": "Descrizione",
        "transactions.colCategory": "Categoria",
        "transactions.colAmount": "Importo",
        "transactions.colActions": "Azioni",
        "transactions.uncategorized": "Senza categoria",
        "transactions.defaultDesc": "Transazione",
        "transactions.page": "Pagina",
        "transactions.of": "di",
        "transactions.prev": "Precedente",
        "transactions.next": "Successiva",
        "transactions.edit": "Modifica",
        "transactions.typeLabel": "Tipo",
        "transactions.expense": "Uscita",
        "transactions.income": "Entrata",
        "transactions.amountLabel": "Importo",
        "transactions.amountPlaceholder": "0.00",
        "transactions.descLabel": "Descrizione",
        "transactions.descPlaceholder": "es. Cibo",
        "transactions.descOptional": "Descrizione (opzionale)",
        "transactions.whatFor": "Per cosa era questo?",
        "transactions.dateLabel": "Data",
        "transactions.categoryLabel": "Categoria",
        "transactions.selectCategory": "Seleziona...",
        "categories.title": "Tue categorie",
        "categories.new": "Nuova",
        "categories.empty": "Nessuna categoria.",
        "categories.errorSave": "Errore",
        "categories.confirmDelete": "Eliminare?",
        "categories.errorDelete": "Errore",
        "categories.income": "Entrate",
        "categories.expense": "Uscita",
        "categories.edit": "Modifica",
        "categories.nameLabel": "Nome",
        "categories.namePlaceholder": "Nome",
        "categories.typeLabel": "Tipo",
        "categories.colorLabel": "Colore",
        "users.title": "Gestione utenti",
        "users.users": "Utenti",
        "users.subtitle": "Gestisci tutti gli utenti",
        "users.id": "ID",
        "users.username": "Utente",
        "users.email": "Email",
        "users.actions": "Azioni",
        "users.changePassword": "Cambia password",
        "users.delete": "Elimina account",
        "users.confirmDelete": "Sei sicuro di voler eliminare questo utente?",
        "users.errorFetch": "Impossibile caricare gli utenti",
        "users.errorDelete": "Impossibile eliminare l'utente",
        "users.errorPassword": "Impossibile aggiornare la password",
        "users.newPassword": "Nuova password",
        "users.passwordUpdated": "Password aggiornata con successo",
        "users.userDeleted": "Utente eliminato con successo",
        "users.deleteConfirm": "Sei sicuro di voler eliminare l'utente \"{0}\"?",
        "users.deleteSuccess": "Utente eliminato con successo",
        "users.updatePassword": "Imposta password per \"{0}\"",
        "users.passwordPlaceholder": "Inserisci nuova password...",
        "users.passwordEmpty": "La password non può essere vuota",
        "users.passwordShort": "Almeno 8 caratteri richiesti",
        "users.passwordSuccess": "Password aggiornata",
        "users.admin": "Amministratore",
        "users.user": "Utente",
        "users.refresh": "Aggiorna",
        "users.noUsers": "Nessun utente trovato.",
        "common.cancel": "Cancellare",
        "common.update": "Aggiorna",
        "common.create": "Crea",
        "common.save": "Salva",
        "common.success": "Successo!",
        "common.error": "Errore",
        "common.deleted": "Eliminato!",
        "common.delete": "Sì, elimina!",
        "common.invalidAmount": "Inserire un importo valido superiore a 0",
        "settings.title": "Impostazioni",
        "settings.subtitle": "Gestisci preferenze",
        "settings.personalInfo": "Info personali",
        "settings.username": "Nome utente",
        "settings.email": "Email",
        "settings.appPreferences": "Preferenze app",
        "settings.currency": "Valuta",
        "settings.currencyDesc": "Scegli valuta",
        "settings.language": "Lingua",
        "settings.languageDesc": "Lingua interfaccia",
        "settings.theme": "Tema",
        "settings.themeDesc": "Variante UI",
        "settings.saveAll": "Salvare",
        "settings.security": "Sicurezza",
        "settings.securityRec": "Raccomandazione",
        "settings.securityDesc": "Usa 8 caratteri.",
        "settings.currentPassword": "Password attuale",
        "settings.newPassword": "Nuova password",
        "settings.confirmPassword": "Conferma password",
        "settings.forgotPassword": "Dimenticata?",
        "settings.updatePassword": "Aggiorna password",
        "transactions.newExpense": "Aggiungi spesa",
        "transactions.newIncome": "Aggiungi entrata",
        "transactions.history": "Cronologia transazioni",
        "transactions.matches": "Corrispondenze trovate",
        "transactions.fastSearch": "Ricerca rapida per descrizione...",
        "common.all": "Tutti",
        "common.invalidAmount": "Inserire un importo valido superiore a 0",
        "lang.english": "Inglese",
        "lang.spanish": "Spagnolo",
        "lang.french": "Francese",
        "lang.german": "Tedesco",
        "lang.italian": "Italiano",
        "lang.portuguese": "Portoghese"
    },
    PORTUGUESE: {
        "nav.overview": "Visão geral",
        "nav.analytics": "Analítica",
        "nav.transactions": "Transações",
        "nav.users": "Usuários",
        "nav.settings": "Configurações",
        "nav.logout": "Sair",
        "login.checkData": "Verifique seus dados.",
        "login.heroTitle1": "Assuma o controle",
        "login.heroTitle2": "futuro",
        "login.heroSubtitle": "Visualize e alcance seus objetivos.",
        "login.security": "Máxima segurança",
        "login.securityDesc": "Dados criptografados",
        "login.growth": "Crescimento inteligente",
        "login.growthDesc": "Análise em tempo real",
        "login.createAccount": "Criar conta",
        "login.signIn": "Entrar",
        "login.enterDetails": "Digite os detalhes",
        "login.signInDesc": "Acesse sua conta",
        "login.username": "Usuário",
        "login.usernamePlaceholder": "Seu usuário",
        "login.email": "Email",
        "login.emailPlaceholder": "email@email.com",
        "login.password": "Senha",
        "login.alreadyHaveAccount": "Já possui conta?",
        "login.noAccount": "Ainda não?",
        "dashboard.overview": "Visão geral",
        "dashboard.welcome": "Bem-vindo de volta, {0}",
        "dashboard.welcomeMobile": "Bem-vindo, {0} ",
        "dashboard.totalBalance": "Saldo total",
        "dashboard.vsLastMonth": "vs mês passado",
        "dashboard.monthlyIncome": "Rendimento mensal",
        "dashboard.monthlyExpenses": "Despesas mensais",
        "dashboard.analytics": "Analítica",
        "dashboard.incomeVsExpenses": "Receitas vs Despesas",
        "dashboard.thisYear": "Este ano",
        "dashboard.last6Months": "Últimos 6 meses",
        "dashboard.thisMonth": "Este mês",
        "dashboard.recentTransactions": "Recentes",
        "dashboard.seeAll": "Ver tudo",
        "dashboard.noTransactions": "Nenhuma transação.",
        "analytics.title": "Analítica",
        "analytics.subtitle": "Visão aprofundada.",
        "analytics.thismonth": "Este mês",
        "analytics.last3months": "Últimos 3 meses",
        "analytics.last6months": "Últimos 6 meses",
        "analytics.thisyear": "Este ano",
        "analytics.custom": "Personalizado",
        "analytics.from": "De",
        "analytics.to": "Até",
        "analytics.totalIncome": "Rendimentos",
        "analytics.totalExpenses": "Despesas",
        "analytics.netBalance": "Saldo líquido",
        "analytics.trendTitle": "Tendência",
        "analytics.categoryTitle": "Despesas por categoria",
        "analytics.distributionTitle": "Distribuição",
        "analytics.distributionDesc": "Parcela de despesas",
        "analytics.insightTitle": "Ideia financeira",
        "analytics.insightMessage": "Maior despesa \"{0}\" {1}{2}.",
        "analytics.insightEmpty": "Sem dados.",
        "analytics.savingsScore": "Pontuação: {0}/100",
        "transactions.hub": "Centro de transações",
        "transactions.hubDesc": "Gerencie operações",
        "transactions.tabTransactions": "Transações",
        "transactions.tabCategories": "Categorias",
        "transactions.title": "Suas transações",
        "transactions.new": "Nova transação",
        "transactions.errorSave": "Erro: {0}",
        "transactions.confirmDelete": "Tem certeza que deseja apagar?",
        "transactions.errorDelete": "Erro ao deletar",
        "transactions.searchPlaceholder": "Pesquisar...",
        "transactions.to": "até",
        "transactions.filterTitle": "Filtro",
        "transactions.reset": "Limpar",
        "transactions.empty": "Nenhuma transação encontrada.",
        "transactions.updated": "Transação atualizada com sucesso",
        "transactions.saved": "Transação salva com sucesso",
        "transactions.confirmDeleteTitle": "Tem certeza?",
        "transactions.deletedMsg": "A transação foi excluída.",
        "transactions.updated": "Transação atualizada com sucesso",
        "transactions.saved": "Transação salva com sucesso",
        "transactions.confirmDeleteTitle": "Tem certeza?",
        "transactions.deletedMsg": "A transação foi excluída.",
        "transactions.amountPlaceholder": "0.00",
        "users.title": "Gestão de usuários",
        "users.users": "Usuários",
        "users.subtitle": "Gerencie todos os usuários",
        "users.id": "ID",
        "users.username": "Usuário",
        "users.email": "Email",
        "users.actions": "Ações",
        "users.changePassword": "Mudar senha",
        "users.delete": "Excluir conta",
        "users.confirmDelete": "Tem certeza que deseja apagar este usuário?",
        "users.errorFetch": "Falha ao carregar usuários",
        "users.errorDelete": "Falha ao excluir usuário",
        "users.errorPassword": "Falha ao atualizar senha",
        "users.newPassword": "Nova senha",
        "users.passwordUpdated": "Senha atualizada com sucesso",
        "users.userDeleted": "Usuário excluído com sucesso",
        "users.deleteConfirm": "Tem certeza que deseja excluir o usuário \"{0}\"?",
        "users.deleteSuccess": "Usuário excluído com sucesso",
        "users.updatePassword": "Definir senha para \"{0}\"",
        "users.passwordPlaceholder": "Digite a nova senha...",
        "users.passwordEmpty": "A senha não pode estar vazia",
        "users.passwordShort": "Mínimo de 8 caracteres",
        "users.passwordSuccess": "Senha atualizada",
        "users.admin": "Administrador",
        "users.user": "Usuário",
        "users.refresh": "Atualizar",
        "users.noUsers": "Nenhum usuário encontrado.",
        "transactions.colDate": "Data",
        "transactions.colDescription": "Descrição",
        "transactions.colCategory": "Categoria",
        "transactions.colAmount": "Quantia",
        "transactions.colActions": "Ações",
        "transactions.uncategorized": "Sem categoria",
        "transactions.defaultDesc": "Transação",
        "transactions.page": "Página",
        "transactions.of": "de",
        "transactions.prev": "Anterior",
        "transactions.next": "Próxima",
        "transactions.edit": "Editar transação",
        "transactions.typeLabel": "Tipo",
        "transactions.expense": "Despesa",
        "transactions.income": "Receita",
        "transactions.amountLabel": "Quantia",
        "transactions.amountPlaceholder": "0.00",
        "transactions.descLabel": "Descrição",
        "transactions.descPlaceholder": "ex: Supermercado",
        "transactions.descOptional": "Descrição (opcional)",
        "transactions.whatFor": "Para que foi isso?",
        "transactions.dateLabel": "Data",
        "transactions.categoryLabel": "Categoria",
        "transactions.selectCategory": "Selecione...",
        "categories.title": "Suas categorias",
        "categories.new": "Nova categoria",
        "categories.empty": "Nenhuma categoria.",
        "categories.errorSave": "Erro",
        "categories.confirmDelete": "Apagar categoria?",
        "categories.errorDelete": "Erro",
        "categories.income": "Receita",
        "categories.expense": "Despesa",
        "categories.edit": "Editar categoria",
        "categories.nameLabel": "Nome",
        "categories.namePlaceholder": "Nome",
        "categories.typeLabel": "Tipo",
        "categories.colorLabel": "Cor",
        "common.cancel": "Cancelar",
        "common.update": "Atualizar",
        "common.create": "Criar",
        "common.save": "Salvar",
        "settings.title": "Configurações",
        "settings.subtitle": "Gerencie as preferências",
        "settings.personalInfo": "Informações pessoais",
        "settings.username": "Usuário",
        "settings.email": "Email",
        "settings.appPreferences": "Preferências do app",
        "settings.currency": "Moeda",
        "settings.currencyDesc": "Moeda de exibição",
        "settings.language": "Idioma",
        "settings.languageDesc": "Idioma do app",
        "settings.theme": "Tema",
        "settings.themeDesc": "Tema visual",
        "settings.saveAll": "Salvar tudo",
        "settings.security": "Segurança",
        "settings.securityRec": "Recomendação",
        "settings.securityDesc": "Use senha de 8 caracteres.",
        "settings.currentPassword": "Senha atual",
        "settings.newPassword": "Nova senha",
        "settings.confirmPassword": "Confirmar",
        "settings.forgotPassword": "Esqueceu?",
        "settings.updatePassword": "Atualizar senha",
        "transactions.newExpense": "Adicionar despesa",
        "transactions.newIncome": "Adicionar receita",
        "transactions.history": "Histórico de transações",
        "transactions.matches": "Correspondências encontradas",
        "transactions.fastSearch": "Busca rápida por descrição...",
        "common.all": "Tudo",
        "common.invalidAmount": "Insira um valor válido maior que 0",
        "lang.english": "Inglês",
        "lang.spanish": "Espanhol",
        "lang.french": "Francés",
        "lang.german": "Alemão",
        "lang.italian": "Italiano",
        "lang.portuguese": "Português"
    }
};

export function LanguageProvider({ children }) {
    const { user } = useAuth();
    const [currentLang, setCurrentLang] = useState(() => {
        return localStorage.getItem('language')?.toUpperCase() || 'ENGLISH';
    });

    // Sync with user preference from AuthContext
    useEffect(() => {
        if (user?.language) {
            const userLang = user.language.toUpperCase();
            if (translations[userLang] && userLang !== currentLang) {
                setCurrentLang(userLang);
                localStorage.setItem('language', userLang);
            }
        }
    }, [user?.language]);

    useEffect(() => {
        const handleStorageChange = () => {
            const lang = localStorage.getItem('language') || 'ENGLISH';
            if (lang !== currentLang) {
                setCurrentLang(lang);
            }
        };

        window.addEventListener('storage', handleStorageChange);
        return () => window.removeEventListener('storage', handleStorageChange);
    }, [currentLang]);

    const changeLanguage = (langKey) => {
        const normalized = langKey.toUpperCase();
        if (translations[normalized]) {
            setCurrentLang(normalized);
            localStorage.setItem('language', normalized);
        }
    };

    const t = (key, replacements) => {
        const dict = translations[currentLang] || translations['ENGLISH'];
        let text = dict[key] || translations['ENGLISH'][key];

        if (!text) return key;

        if (replacements) {
            if (Array.isArray(replacements)) {
                replacements.forEach((replacement, index) => {
                    text = text.replace(`{${index}}`, replacement);
                });
            } else if (typeof replacements === 'object') {
                Object.keys(replacements).forEach(placeholder => {
                    text = text.replace(`{${placeholder}}`, replacements[placeholder]);
                });
            } else {
                // Single replacement
                text = text.replace('{0}', replacements);
            }
        }

        return text;
    };

    return (
        <LanguageContext.Provider value={{ currentLang, changeLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export const useTranslation = () => useContext(LanguageContext);